### ISSUE TITLE
Breaking changes in 2.0.0

### ISSUE THREAD

**Issue by cjihrig** [continuationlabs/insync#27]
## Breaking Changes

- Remove `noConflict()`. Not needed in Node.
- Remove `nextTick()`. Not needed in Node. Use `process.nextTick()`.
- Remove `setImmediate()`. Not needed in Node. Use JavaScript's `setImmediate()`.
- `filter()`, `filterSeries()`, `reject()`, `rejectSeries()`, `detect()`, `detectSeries()`, `some()`, `every()`, and their aliased functions will now use proper Node errback style callbacks. #19
- `cargo()` is now an instance of a `queue()`.

## Other Changes

- Move to neo-async style waterfalls for increased performance.
- Add a build step using Babel. This was done to use `let`, `const`, and rest parameters.
- Incorporate new async features such as `forEachOf()`, `forEachOfSeries()`, `forEachOfLimit()`, `timesLimit()`. Also, bug fixes and documentation updates.

**Comment by arb** [comment]
## Breaking Changes
- Any method that receives on object with results in a final callback is now a true hash object and *not* a generic JavaScript object. This means, `result.hasOwnProperty()` will throw an error as `result` no longer has that method.
